# Generated by Django 4.2.23 on 2026-01-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Event title in English', max_length=255)),
                ('title_ur', models.CharField(help_text='Event title in Urdu', max_length=255)),
                ('description_en', models.TextField(blank=True, help_text='Event description in English')),
                ('description_ur', models.TextField(blank=True, help_text='Event description in Urdu')),
                ('recurring_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='one_time', help_text='Type of recurring event', max_length=20)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], help_text='Day of week for weekly/monthly recurring events (0=Sunday, 4=Thursday)', null=True)),
                ('week_of_month', models.IntegerField(blank=True, help_text='Week of month (1-4) for monthly recurring events (e.g., 1 = first Thursday)', null=True)),
                ('event_date', models.DateField(blank=True, help_text='Specific date for one-time events', null=True)),
                ('event_time', models.TimeField(blank=True, help_text='Time of the event', null=True)),
                ('date_text_en', models.CharField(blank=True, help_text="Human-readable date text in English (e.g., 'First Thursday of every month')", max_length=255)),
                ('date_text_ur', models.CharField(blank=True, help_text="Human-readable date text in Urdu (e.g., 'ہر مہینے کی پہلی جمعرات')", max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Show this event on the website')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['order', 'id'],
            },
        ),
    ]
