# Generated by Django 4.2.23 on 2026-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('high', 'High (Red)'), ('medium', 'Medium (Blue)'), ('low', 'Low (Green)'), ('default', 'Default (Blue)')], default='default', help_text='Event priority determines the color indicator on calendar', max_length=20),
        ),
    ]
