# Generated by Django 4.2.23 on 2025-08-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ur', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('description_ur', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='publications/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
