# Generated by Django 4.2.23 on 2025-08-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('urdu_title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('category', models.CharField(choices=[('Bayaan', 'Bayaan'), ('Dhikr', 'Dhikr'), ('Event', 'Event')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_title', models.CharField(max_length=255)),
                ('urdu_title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('category', models.CharField(choices=[('Bayaan', 'Bayaan'), ('Dhikr', 'Dhikr'), ('Event', 'Event')], max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
