# Generated by Django 4.2.23 on 2025-08-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_audios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_file',
            new_name='audio_url',
        ),
        migrations.AlterField(
            model_name='audio',
            name='category',
            field=models.CharField(choices=[('Bayaan', 'Bayaan'), ('Dhikr', 'Dhikr'), ('Event', 'Event')], max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Bayaan', 'Bayaan'), ('Dhikr', 'Dhikr'), ('Event', 'Event')], max_length=50),
        ),
    ]
