# Generated by Django 4.2.23 on 2025-08-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_audios', '0002_rename_audio_file_audio_audio_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ur', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('bayaan', 'Bayaan'), ('dhikr', 'Dhikr'), ('event', 'Event')], max_length=20)),
                ('file', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
