# Generated by Django 4.2.23 on 2025-08-17 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_uploaded_at_alter_collection_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
