# Generated by Django 4.2.23 on 2025-08-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ur', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ur', models.TextField()),
                ('file', models.FileField(upload_to='publications/files/')),
                ('cover', models.ImageField(upload_to='publications/covers/')),
                ('category', models.CharField(choices=[('book', 'Book'), ('risala', 'Risala'), ('other', 'Other')], max_length=10)),
            ],
        ),
    ]
