# Generated by Django 4.2.23 on 2025-08-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('risala', 'Risala'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='publications/covers/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='file',
            field=models.FileField(upload_to='publications/'),
        ),
    ]
