# Generated by Django 4.2.23 on 2025-08-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_category_alter_publication_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('risala', 'Risala'), ('other', 'Other')], default='book', max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_en',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_ur',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
