# Generated by Django 4.2.23 on 2025-08-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('risala', 'Risala'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(default='publications/covers/default.png', upload_to='publications/covers/'),
        ),
    ]
