# Generated by Django 4.2.23 on 2026-01-17 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Section title in English', max_length=255)),
                ('title_ur', models.CharField(help_text='Section title in Urdu', max_length=255)),
                ('content_en', models.TextField(blank=True, help_text='Main content in English (optional if using subsections)')),
                ('content_ur', models.TextField(blank=True, help_text='Main content in Urdu (optional if using subsections)')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('default_open', models.BooleanField(default=False, help_text='Should this section be open by default?')),
                ('is_active', models.BooleanField(default=True, help_text='Show this section on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutSubSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(help_text='Sub-section title in English', max_length=255)),
                ('title_ur', models.CharField(help_text='Sub-section title in Urdu', max_length=255)),
                ('content_en', models.TextField(help_text='Sub-section content in English')),
                ('content_ur', models.TextField(help_text='Sub-section content in Urdu')),
                ('order', models.IntegerField(default=0, help_text='Display order within the parent section')),
                ('is_active', models.BooleanField(default=True, help_text='Show this sub-section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='about.aboutsection')),
            ],
            options={
                'verbose_name': 'About Sub-Section',
                'verbose_name_plural': 'About Sub-Sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
