# Generated by Django 4.2.23 on 2026-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentNasheen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Full name in English', max_length=255)),
                ('name_ur', models.CharField(help_text='Full name in Urdu', max_length=255)),
                ('description_en', models.TextField(help_text='Description/biography in English')),
                ('description_ur', models.TextField(help_text='Description/biography in Urdu')),
                ('image', models.ImageField(blank=True, help_text='Profile image', null=True, upload_to='nasheen/')),
                ('is_active', models.BooleanField(default=True, help_text='Is this the current active Nasheen?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Current Nasheen',
                'verbose_name_plural': 'Current Nasheen',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviousNasheen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(help_text='Name in English', max_length=255)),
                ('name_ur', models.CharField(help_text='Name in Urdu', max_length=255)),
                ('order', models.IntegerField(help_text='Succession order (1 = first, 2 = second, etc.)')),
                ('is_present', models.BooleanField(default=False, help_text='Is this the current/present Nasheen?')),
                ('is_active', models.BooleanField(default=True, help_text='Show in lineage tree')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Previous Nasheen',
                'verbose_name_plural': 'Previous Nasheens',
                'ordering': ['order', 'id'],
            },
        ),
    ]
